import type { AlarmRecord } from './types';

const mockAlarms: AlarmRecord[] = [
  {
    id: 'alarm-001',
    site: 'Riverside Primary School',
    device: 'Water Meter A1',
    category: 'Water',
    severity: 'High',
    description: 'Water leakage detected at main inlet valve.',
    timestamp: '2026-02-15 09:42 AM',
    status: 'Open',
  },
  {
    id: 'alarm-002',
    site: 'Riverside Primary School',
    device: 'Power Meter B4',
    category: 'Electrical',
    severity: 'Medium',
    description: 'Power utilization above baseline for 45 minutes.',
    timestamp: '2026-02-15 10:18 AM',
    status: 'Acknowledged',
  },
  {
    id: 'alarm-003',
    site: 'Riverside Primary School',
    device: 'Pump Room Sensor',
    category: 'Mechanical',
    severity: 'Low',
    description: 'Vibration threshold exceeded on pump 2.',
    timestamp: '2026-02-15 10:54 AM',
    status: 'Open',
  },
  {
    id: 'alarm-004',
    site: 'Hillcrest Campus',
    device: 'HVAC Unit 7',
    category: 'HVAC',
    severity: 'High',
    description: 'Supply temperature outside safe range.',
    timestamp: '2026-02-15 11:21 AM',
    status: 'Open',
  },
  {
    id: 'alarm-005',
    site: 'Hillcrest Campus',
    device: 'Lighting Panel 3',
    category: 'Electrical',
    severity: 'Medium',
    description: 'Lighting circuit overload risk detected.',
    timestamp: '2026-02-15 11:34 AM',
    status: 'Resolved',
  },
  {
    id: 'alarm-006',
    site: 'Lakeside Annex',
    device: 'Generator A',
    category: 'Electrical',
    severity: 'High',
    description: 'Maximum demand current exceeded 20% threshold.',
    timestamp: '2026-02-15 11:48 AM',
    status: 'Acknowledged',
  },
  {
    id: 'alarm-007',
    site: 'Lakeside Annex',
    device: 'Water Meter C2',
    category: 'Water',
    severity: 'Low',
    description: 'Daily flow variance above seasonal average.',
    timestamp: '2026-02-15 12:05 PM',
    status: 'Open',
  },
  {
    id: 'alarm-008',
    site: 'Riverside Primary School',
    device: 'Battery Backup',
    category: 'Electrical',
    severity: 'Medium',
    description: 'Battery health below recommended threshold.',
    timestamp: '2026-02-15 12:18 PM',
    status: 'Open',
  },
  {
    id: 'alarm-009',
    site: 'Hillcrest Campus',
    device: 'Elevator Controller',
    category: 'Operations',
    severity: 'Low',
    description: 'Manual override engaged by maintenance crew.',
    timestamp: '2026-02-15 12:31 PM',
    status: 'Resolved',
  },
];

export async function getAlarms(): Promise<AlarmRecord[]> {
  return mockAlarms;
}
